package com.club.service;
import com.club.dto.*; import com.club.entity.*; import com.club.exception.BusinessException; import com.club.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.List;
@Service @RequiredArgsConstructor public class AccesoService {
 private final PersonaRepository personaRepository; private final RegistroAccesoRepository accesoRepository;
 @Transactional public AccesoResponse registrarEntrada(RegistrarAccesoDTO dto){Persona p=personaRepository.findById(dto.personaId()).orElseThrow(()->new BusinessException("Persona no encontrada."));if(p.isEliminado())throw new BusinessException("La persona está dada de baja.");if(accesoRepository.existsByPersonaIdAndHoraSalidaIsNull(p.getId()))throw new BusinessException("La persona ya tiene un ingreso abierto.");RegistroAcceso a=new RegistroAcceso();a.setPersona(p);a.setFecha(LocalDate.now());a.setHoraEntrada(LocalTime.now().withNano(0));return toDto(accesoRepository.save(a));}
 @Transactional public AccesoResponse registrarSalida(String id){RegistroAcceso a=accesoRepository.findById(id).orElseThrow(()->new BusinessException("Registro de acceso no encontrado."));if(a.getHoraSalida()!=null)throw new BusinessException("La salida ya fue registrada.");a.setHoraSalida(LocalTime.now().withNano(0));return toDto(accesoRepository.save(a));}
 @Transactional(readOnly=true) public List<AccesoResponse> listar(){return accesoRepository.findAllByOrderByFechaDescHoraEntradaDesc().stream().map(this::toDto).toList();}
 @Transactional(readOnly=true) public List<AccesoResponse> listarPorPersona(String id){personaRepository.findById(id).orElseThrow(()->new BusinessException("Persona no encontrada."));return accesoRepository.findByPersonaIdOrderByFechaDescHoraEntradaDesc(id).stream().map(this::toDto).toList();}
 private AccesoResponse toDto(RegistroAcceso a){long m=a.getHoraEntrada()!=null&&a.getHoraSalida()!=null?Duration.between(a.getHoraEntrada(),a.getHoraSalida()).toMinutes():0;return new AccesoResponse(a.getId(),a.getPersona().getId(),a.getPersona().getNombre()+" "+a.getPersona().getApellido(),a.getFecha(),a.getHoraEntrada(),a.getHoraSalida(),m);}
}
