package com.club.service;
import com.club.dto.*; import com.club.entity.*; import com.club.enumeration.*; import com.club.exception.BusinessException; import com.club.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.time.LocalDate; import java.time.YearMonth; import java.util.List;
@Service @RequiredArgsConstructor public class PagoService {
 private final GrupoFamiliarRepository familiaRepository; private final PagoRepository pagoRepository;
 @Transactional public PagoResponse registrarPago(String familiaId,RegistrarPagoDTO dto){ if(dto==null) throw new BusinessException("Los datos del pago son obligatorios."); YearMonth periodo=parsePeriodo(dto.periodo()); GrupoFamiliar f=familiaRepository.findById(familiaId).orElseThrow(()->new BusinessException("Grupo familiar no encontrado.")); if(dto.importe()==null||dto.importe().compareTo(BigDecimal.ZERO)<=0) throw new BusinessException("El importe debe ser mayor a cero."); if(dto.medioPago()==null) throw new BusinessException("Debe indicar el medio de pago."); if(pagoRepository.existsByGrupoFamiliarIdAndPeriodo(familiaId,periodo.toString())) throw new BusinessException("La cuota de ese período ya está registrada."); validarReferencia(dto.medioPago(),dto.referencia()); Pago p=new Pago(periodo.toString(),dto.importe(),dto.medioPago(),dto.referencia()==null?null:dto.referencia().trim()); p.setGrupoFamiliar(f); p.setFechaPago(LocalDate.now()); p.setEstado(EstadoPago.REGISTRADO); try{return toDto(pagoRepository.save(p));}catch(DataIntegrityViolationException e){throw new BusinessException("La cuota de ese período ya está registrada.");}}
 @Transactional(readOnly=true) public List<PagoResponse> listarPorFamilia(String familiaId){familiaRepository.findById(familiaId).orElseThrow(()->new BusinessException("Grupo familiar no encontrado."));return pagoRepository.findByGrupoFamiliarIdOrderByFechaPagoDesc(familiaId).stream().map(this::toDto).toList();}
 @Transactional(readOnly=true) public List<PagoResponse> listarTodos(){return pagoRepository.findAll().stream().map(this::toDto).toList();}
 @Transactional(readOnly=true) public PagoResponse obtener(String id){return toDto(pagoRepository.findById(id).orElseThrow(()->new BusinessException("Pago no encontrado.")));}
 @Transactional public void anular(String id){Pago p=pagoRepository.findById(id).orElseThrow(()->new BusinessException("Pago no encontrado."));if(p.getEstado()==EstadoPago.ANULADO)throw new BusinessException("El pago ya está anulado.");p.setEstado(EstadoPago.ANULADO);}
 private YearMonth parsePeriodo(String v){try{return YearMonth.parse(v);}catch(Exception e){throw new BusinessException("El período debe tener formato YYYY-MM.");}}
 private void validarReferencia(MedioPago m,String r){if((m==MedioPago.TRANSFERENCIA||m==MedioPago.MERCADO_PAGO)&&(r==null||r.isBlank()))throw new BusinessException("La referencia es obligatoria para transferencia y Mercado Pago.");}
 private PagoResponse toDto(Pago p){return new PagoResponse(p.getId(),p.getGrupoFamiliar().getId(),p.getGrupoFamiliar().getNombre(),p.getPeriodo(),p.getImporte(),p.getMedioPago(),p.getEstado(),p.getFechaPago(),p.getReferencia());}
}
