package com.club.controller;
import com.club.dto.*; import com.club.service.*; import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.http.*; import org.springframework.stereotype.Controller; import org.springframework.ui.Model; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile; import org.springframework.web.servlet.mvc.support.RedirectAttributes; import java.util.List;
@RestController @RequestMapping("/api/socios") @RequiredArgsConstructor class SocioRestController { private final SocioService service; @PostMapping @ResponseStatus(HttpStatus.CREATED) public SocioResponse crear(@Valid @RequestBody RegistrarSocioDTO d){return service.registrar(d);} @GetMapping public List<SocioResponse> listar(){return service.listar();} @GetMapping("/{id}") public SocioResponse obtener(@PathVariable String id){return service.obtener(id);} @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void baja(@PathVariable String id){service.darDeBaja(id);} @PutMapping("/{id}") public SocioResponse editar(@PathVariable String id,@Valid @RequestBody EditarSocioDTO d){return service.editar(id,d);} @PutMapping("/{id}/reactivar") public SocioResponse reactivar(@PathVariable String id){service.reactivar(id);return service.obtener(id);} }
@Controller @RequestMapping("/socios") @RequiredArgsConstructor public class SocioController { private final SocioService service; private final ImagenService imagenService;
 @GetMapping public String listar(Model m){m.addAttribute("socios",service.listarTodos());return "socios/lista";} @GetMapping("/nuevo") public String nuevo(Model m){m.addAttribute("form",new SocioForm());return "socios/form";}
 @PostMapping public String crear(@Valid SocioForm f,Model m,RedirectAttributes ra){try{service.registrar(new RegistrarSocioDTO(f.getNombre(),f.getApellido(),f.getEmail(),f.getTelefono(),f.getFechaNacimiento()));ra.addFlashAttribute("ok","Socio registrado correctamente.");return "redirect:/socios";}catch(RuntimeException e){m.addAttribute("error",e.getMessage());return "socios/form";}}
 @PostMapping("/{id}/baja") public String baja(@PathVariable String id,RedirectAttributes ra){try{service.darDeBaja(id);ra.addFlashAttribute("ok","Socio dado de baja.");}catch(RuntimeException e){ra.addFlashAttribute("error",e.getMessage());}return "redirect:/socios";}
 @PostMapping("/{id}/reactivar") public String reactivar(@PathVariable String id,RedirectAttributes ra){try{service.reactivar(id);ra.addFlashAttribute("ok","Socio reactivado.");}catch(RuntimeException e){ra.addFlashAttribute("error",e.getMessage());}return "redirect:/socios";}
 @GetMapping("/{id}/editar") public String editarForm(@PathVariable String id,Model m){SocioResponse s=service.obtener(id);SocioForm f=new SocioForm();f.setNombre(s.nombre());f.setApellido(s.apellido());f.setEmail(s.email());f.setTelefono(s.telefono());f.setFechaNacimiento(s.fechaNacimiento());m.addAttribute("socio",s);m.addAttribute("form",f);return "socios/editar";}
 @PostMapping("/{id}/editar") public String editar(@PathVariable String id,SocioForm f,Model m,RedirectAttributes ra){try{service.editar(id,new EditarSocioDTO(f.getNombre(),f.getApellido(),f.getEmail(),f.getTelefono(),f.getFechaNacimiento()));ra.addFlashAttribute("ok","Socio actualizado correctamente.");return "redirect:/socios/"+id;}catch(RuntimeException e){m.addAttribute("error",e.getMessage());m.addAttribute("socio",service.obtener(id));m.addAttribute("form",f);return "socios/editar";}}
 @GetMapping("/{id}") public String detalle(@PathVariable String id,Model m){m.addAttribute("socio",service.obtener(id));return "socios/detalle";}
 @PostMapping(value="/{id}/imagen",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public String imagen(@PathVariable String id,@RequestParam MultipartFile archivo,RedirectAttributes ra){try{imagenService.guardarEnPersona(id,new ImagenUploadDTO(archivo.getOriginalFilename(),archivo.getContentType(),archivo.getBytes()));ra.addFlashAttribute("ok","Imagen guardada.");}catch(Exception e){ra.addFlashAttribute("error",e.getMessage());}return "redirect:/socios/"+id;}
 @PostMapping("/{id}/imagen/eliminar") public String eliminarImagen(@PathVariable String id,RedirectAttributes ra){try{imagenService.eliminarDePersona(id);ra.addFlashAttribute("ok","Imagen eliminada.");}catch(RuntimeException e){ra.addFlashAttribute("error",e.getMessage());}return "redirect:/socios/"+id;}
}
